### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by brucewuu520** [wasabeef/Blurry#2]
error log:
java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
            at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:56)
            at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:58)
            at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:27)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v8.renderscript.RenderScript" on path: DexPathList[[zip file "/data/app/com.brucewuu.android.mdog-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at jp.wasabeef.blurry.internal.Blur.rs(Blur.java:56)
            at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:58)
            at jp.wasabeef.blurry.internal.BlurTask.doInBackground(BlurTask.java:27)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
    Suppressed: java.lang.ClassNotFoundException: android.support.v8.renderscript.RenderScript
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 10 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by wasabeef** [comment]
@brucewuu520 
Do you enabled v8.RenderScript?

**Comment by bluemix** [comment]
this happened to me when I used 
    ```buildToolsVersion "23.0.0 RC3"```

**Comment by wasabeef** [comment]
@bluemix 

Hi.
enabled the RenderScript?

```
...
defaultConfig {
  ...

  renderscriptTargetApi 23
  renderscriptSupportModeEnabled true
}
...
```

**Comment by bluemix** [comment]
the problem is that if I enable the renderscript with ```buildToolsVersion "23.0.0 RC3"```, it doesn't allow me to make my project, having an error saying you can't have duplicate definitions of the renderscript enabled both in the library and in the app module. So, I kept went back to ```    buildToolsVersion "22.0.1"``` and having the renderscript enabled in the app, without having any error.

**Comment by wasabeef** [comment]
@bluemix 

OK.  I will try.

**Comment by wasabeef** [comment]
@bluemix 

Look at this :weary:
https://code.google.com/p/android/issues/detail?id=181697

Anyway...
Please build in 22.0.1.

I will wait for the release of a new `buildToolsVersion`.

**Comment by bluemix** [comment]
Ok, thanks @wasabeef

**Comment by wasabeef** [comment]
@brucewuu520 
@bluemix 

Hi. 
`buildToolsVersion 23.0.1` has been released.

**Comment by genielabs** [comment]
hi @wasabeef ,

cannot build with 23.0.1

```
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    defaultConfig {
        applicationId "com.glabs.homegenieplus"
        minSdkVersion 14
        targetSdkVersion 23
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
        versionCode 16
        versionName "1.0"
        signingConfig signingConfigs.config
    }
```

I get the following error:

```
:homegenie-plus:packageDebug
Error:duplicate files during packaging of APK /home/gene/AndroidStudioProjects/HomeGeniePersonal2/homegenie-plus/build/outputs/apk/homegenie-plus-debug-unaligned.apk
	Path in archive: lib/mips/librsjni.so
	Origin 1: /home/gene/AndroidStudioProjects/HomeGeniePersonal2/homegenie-plus/build/intermediates/exploded-aar/jp.wasabeef/fresco-processors/1.1.1/jni/mips/librsjni.so
	Origin 2: /home/gene/Android/Sdk/build-tools/23.0.1/renderscript/lib/packaged/mips/librsjni.so
You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'lib/mips/librsjni.so'
	  }
	}
Error:Execution failed for task ':homegenie-plus:packageDebug'.
> Duplicate files copied in APK lib/mips/librsjni.so
  	File 1: /home/gene/AndroidStudioProjects/HomeGeniePersonal2/homegenie-plus/build/intermediates/exploded-aar/jp.wasabeef/fresco-processors/1.1.1/jni/mips/librsjni.so
  	File 2: /home/gene/Android/Sdk/build-tools/23.0.1/renderscript/lib/packaged/mips/librsjni.so
Information:BUILD FAILED
```

**Comment by genielabs** [comment]
Hi @wasabeef, just found a work-around, but not sure if it's a good solution:
```
    packagingOptions {
        pickFirst 'lib/mips/librsjni.so'
        pickFirst 'lib/mips/libblasV8.so'
        pickFirst 'lib/mips/libRSSupport.so'
        pickFirst 'lib/x86/librsjni.so'
        pickFirst 'lib/x86/libblasV8.so'
        pickFirst 'lib/x86/libRSSupport.so'
        pickFirst 'lib/armeabi-v7a/librsjni.so'
        pickFirst 'lib/armeabi-v7a/libblasV8.so'
        pickFirst 'lib/armeabi-v7a/libRSSupport.so'
        exclude 'META-INF/INDEX.LIST'
    }
```

**Comment by wasabeef** [comment]
@genielabs 

What is the version of `Android Plugin for Gradle`?
Please be on 1.5.0 or later.

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

**Comment by genielabs** [comment]
```
------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.7.0_85 (Oracle Corporation 24.85-b03)
OS:           Linux 3.19.0-37-generic amd64
```
